control "V-94063" do
  title "The ESXi host must enable BPDU filter on the host to prevent being
locked out of physical switch ports with Portfast and BPDU Guard enabled."
  desc  "BPDU Guard and Portfast are commonly enabled on the physical switch to
which the ESXi host is directly connected to reduce the STP convergence delay.
If a BPDU packet is sent from a virtual machine on the ESXi host to the
physical switch so configured, a cascading lockout of all the uplink interfaces
from the ESXi host can occur. To prevent this type of lockout, BPDU Filter can
be enabled on the ESXi host to drop any BPDU packets being sent to the physical
switch. The caveat is that certain SSL VPN which use Windows bridging
capability can legitimately generate BPDU packets. The administrator should
verify that there are no legitimate BPDU packets generated by virtual machines
on the ESXi host prior to enabling BPDU Filter.  If BPDU Filter is enabled in
this situation, enabling Reject Forged Transmits on the virtual switch port
group adds protection against Spanning Tree loops."
  impact 0.3
  tag "severity": nil
  tag "gtitle": "SRG-OS-000480-VMM-002000"
  tag "gid": "V-94063"
  tag "rid": "SV-104149r1_rule"
  tag "stig_id": "ESXI-65-000058"
  tag "fix_id": "F-100311r1_fix"
  tag "cci": ["CCI-000366"]
  tag "nist": ["CM-6 b", "Rev_4"]
  tag "false_negatives": nil
  tag "false_positives": nil
  tag "documentable": false
  tag "mitigations": nil
  tag "severity_override_guidance": false
  tag "potential_impacts": nil
  tag "third_party_tools": nil
  tag "mitigation_controls": nil
  tag "responsibility": nil
  tag "ia_controls": nil
  tag "check": "From the vSphere Web Client select the ESXi Host and go to
Configure >> System >> Advanced System Settings. Select the Net.BlockGuestBPDU
value and verify it is set to 1.

or

From a PowerCLI command prompt while connected to the ESXi host run the
following command:

Get-VMHost | Get-AdvancedSetting -Name Net.BlockGuestBPDU

If the Net.BlockGuestBPDU setting is not set to 1, this is a finding."
  tag "fix": "From the vSphere Web Client select the ESXi Host and go to
Configure >> System >> Advanced System Settings. Click Edit and select the
Net.BlockGuestBPDU value and configure it to 1.

or

From a PowerCLI command prompt while connected to the ESXi host run the
following commands:

Get-VMHost | Get-AdvancedSetting -Name Net.BlockGuestBPDU | Set-AdvancedSetting
-Value 1"
end

